import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import React, { useState } from "react";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>ICES4HU</title>
        <meta
          name="description"
          content="Generated by Student Information System"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Main}>
        <Image
          alt="Hacettepe Logo"
          src="/Hacettepe_Logo.png"
          width="200"
          height="200"
        ></Image>
        <div>Hello world2</div>
      </div>
    </>
  );
}
