import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useState } from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [username, setUsername] = useState();
  const [password, setPassword] = useState();

  const handleUsername = (event: any) => {
    setUsername(event.target.value);
  };
  const handlePassword = (event: any) => {
    setPassword(event.target.value);
  };
  const handleClick = async () => {
    try {
      const response = await axios.get(
        "http://localhost:8080/api/v1/personnel"
      );

      if (response.status === 200) {
        console.log("giiş başarılı");
        // Kullanıcı giriş yaptı, bir sonraki sayfaya yönlendirme yapabilirsiniz.
      }
    } catch (error) {
      console.error(error);
      console.log("hata");
      // Hata mesajı göstermek için bir bildirim kullanabilirsiniz.
    }
    console.log(username);
    console.log(password);
  };

  return (
    <>
      <Head>
        <title>ICES4HU</title>
        <meta
          name="description"
          content="Generated by Student Information System"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Main}>
        <div className={styles.LogIn}>
          <div className={styles.LogInBox}>
            <div className={styles.LogInHeader}>Personel Login Screen</div>
            <div className={styles.Input}>
              <input
                onChange={(e: any) => handleUsername(e)}
                className={styles.Username}
                placeholder="Lütfen Kullanıcı Adınızı Girin"
              />
              <input
                className={styles.Password}
                placeholder="Lütfen Şifrenizi Girin"
                type="password"
                onChange={(e: any) => handlePassword(e)}
              />
            </div>
            <div style={{ display: "flex", justifyContent: "center" }}>
              <button onClick={handleClick} className={styles.SubmitButton}>
                LogIn
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
