server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/codeer
    username: codeer
    password: codeerpass
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    allow-circular-references: true
    web-application-type: servlet
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

application:
  security:
    jwt:
      secret-key: 472B4B6250655368566D597133743677397A24432646294A404D635166546A57
      expiration: 86400000 # a day
      admin-token-expiration: 8640000000 # 100 days
      admin-password: abc1234
      refresh-token:
        expiration: 604800000 # 7 days
